### ISSUE TITLE
功能上的建议

### ISSUE THREAD

**Issue by leecoooo** [eric2788/vup_monitors#17]
1. 监控或中止房间时回复消息显示该直播间用户uid和用户昵称
2. 新增或者移除高亮用户时回复消息显示用户uid和用户昵称
2. 显示列表时候显示用户uid和用户昵称
以方便管理，不然显示一堆uid很难分辨是哪个。

**Comment by eric2788** [comment]
可以，但要做快取来储存uid和用户名称，防止请求用户资讯频繁。
但如果途中用户改名了可能没办法检测到，直到移除后再添加，这种情况能否接受？

**Comment by leecoooo** [comment]
> 

我觉得可以，一般不会有主播频繁改名,建议设置一个比较长的时间定时刷新一下.
