### ISSUE TITLE
建议支持QQ频道

### ISSUE THREAD

**Issue by leecoooo** [eric2788/vup_monitors#28]
我看到新版go-cqhttp已经可以输出QQ频道的内容，希望可以绑定在某个QQ频道的子频道。

**Comment by eric2788** [comment]
@Marxel-cn 你要考慮看看嗎？我最近太忙

**Comment by eric2788** [comment]
看了看go-cqhttp的guild文件，他們那邊目前還是測試階段，因此這個功能應該不會很快更新

**Comment by Marxel-cn** [comment]
#37

**Comment by Marxel-cn** [comment]
另外提一句，旧的用户信息API
https://api.bilibili.com/x/space/acc/info?mid=${uid}&jsonp=jsonp
已经基本不可用，建议换一下，如
https://api.bilibili.com/x/web-interface/card?mid=${uid}&jsonp=jsonp
然后取其中的card

**Comment by Marxel-cn** [comment]
> #37

注：如果频道收不到消息，可以尝试重启go-cqhttp，好像频道列表会在启动时重新加载
当然bot不能自行加入频道，所以如果所属的频道有变化，都建议重启一下go-cqhttp

**Comment by eric2788** [comment]
> https://api.bilibili.com/x/space/acc/info?mid=${uid}&jsonp=jsonp

我还可以用耶

**Comment by eric2788** [comment]
@leecoooo 有没有空帮我测试一下这个有频道的版本: https://github.com/eric2788/vup_monitors/suites/11100254906/artifacts/565244864

使用方式: #37
