### ISSUE TITLE
新增不了高亮名单

### ISSUE THREAD

**Issue by leecoooo** [eric2788/vup_monitors#29]
!高亮 新增 12345 54321

回复

找不到用户 12345

其他都正常

**Comment by eric2788** [comment]
有检查一下那个用户id是否存在？

**Comment by leecoooo** [comment]
> 有检查一下那个用户id是否存在？

有的，什么ID都不行，都是报找不到

**Comment by leecoooo** [comment]
> 有检查一下那个用户id是否存在？

刚才试过又可以了，我猜是被风控了
