### ISSUE TITLE
关于注视和高亮的问题 (無法添加注視和高亮)

### ISSUE THREAD

**Issue by KOUymA** [eric2788/vup_monitors#31]
想问一下 注释和高亮的用户ID是b站的UID吗？使用了uid之后是出现找不到用户ID的提示

**Comment by eric2788** [comment]
你需要先監聽直播間，才可以使用高亮

**Comment by KOUymA** [comment]
> 你需要先監聽直播間，才可以使用高亮

已经监听了a直播间，是在注视的时候 添加a的用户id的时候 提示用户不存在 
监听直播间用的是直播间ID 注视和高亮我用的是uid 应该没有理解错吧？

**Comment by eric2788** [comment]
> > 你需要先監聽直播間，才可以使用高亮
> 
> 已经监听了a直播间，是在注视的时候 添加a的用户id的时候 提示用户不存在 监听直播间用的是直播间ID 注视和高亮我用的是uid 应该没有理解错吧？

對的

**Comment by KOUymA** [comment]
> > > 你需要先監聽直播間，才可以使用高亮
> > 
> > 
> > 已经监听了a直播间，是在注视的时候 添加a的用户id的时候 提示用户不存在 监听直播间用的是直播间ID 注视和高亮我用的是uid 应该没有理解错吧？
> 
> 對的

比如拿lulu做例子 21013446是lulu的直播间id 387636363是lulu的uid 
![image](https://user-images.githubusercontent.com/72074577/200172882-070d70a3-e36e-4ad2-b7de-d2bdc4fe3447.png)
这样的操作后 就提示找不到用户 而且监听直播间好像也没有相应的效果
日志信息是这样
![image](https://user-images.githubusercontent.com/72074577/200172997-a90519ed-05c2-40a8-b203-b2a54f2839a4.png)

**Comment by eric2788** [comment]
那應該有機會是b站api請求那邊有問題導致無法識別，我有空看看

**Comment by spicyrnilk** [comment]
遇到相同的问题。

**Comment by eric2788** [comment]
@spicyrnilk @KOUymA 
试试这个测试版本: https://github.com/eric2788/vup_monitors/suites/9156805716/artifacts/426159027

**Comment by KOUymA** [comment]
> @spicyrnilk @KOUymA 试试这个测试版本: https://github.com/eric2788/vup_monitors/suites/9156805716/artifacts/426159027

感谢大佬 辛苦了
刚刚测了一下 添加注视&高亮已经没有问题了
不过开播提醒或者进入直播间的提示应该还存在问题
日志信息如下
![image](https://user-images.githubusercontent.com/72074577/200227602-8198401d-ece3-4231-bba3-4e21e61f2087.png)

**Comment by eric2788** [comment]
> 不过开播提醒或者进入直播间的提示应该还存在问题

什么问题？开播提醒的话有在config启用？

**Comment by eric2788** [comment]
> > @spicyrnilk @KOUymA 试试这个测试版本: https://github.com/eric2788/vup_monitors/suites/9156805716/artifacts/426159027
> 
> 感谢大佬 辛苦了 刚刚测了一下 添加注视&高亮已经没有问题了 不过开播提醒或者进入直播间的提示应该还存在问题 日志信息如下 ![image](https://user-images.githubusercontent.com/72074577/200227602-8198401d-ece3-4231-bba3-4e21e61f2087.png)

另外这些info讯息没太大帮助，你可以在config那边打开debug mode这样会更详细一些

**Comment by KOUymA** [comment]
> 

好的 开播提醒有设置 结果没推送开播的提醒
![image](https://user-images.githubusercontent.com/72074577/200229620-5d7e61a2-ddf6-4969-a864-3574ad7c7655.png)

**Comment by eric2788** [comment]
> > 不过开播提醒或者进入直播间的提示应该还存在问题
> 
> 什么问题？开播提醒的话有在config启用？

懂了，看来也是更验证有关的，等我发布下一个测试版本你再试试

**Comment by eric2788** [comment]
> > 
> 
> 好的 开播提醒有设置 结果没推送开播的提醒 ![image](https://user-images.githubusercontent.com/72074577/200229620-5d7e61a2-ddf6-4969-a864-3574ad7c7655.png)

開播提醒是要同時新增直播間和高亮之後才有的

**Comment by eric2788** [comment]
新測試版本: https://github.com/eric2788/vup_monitors/suites/9159196161/artifacts/426389885
可以先試用幾天，有問題再告訴我
如果沒問題這幾天就會更新

**Comment by eric2788** [comment]
如果沒問題的話，明天就會更新

**Comment by KOUymA** [comment]
> 如果沒問題的話，明天就會更新

测试版本这几天使用都没出现问题
