### ISSUE TITLE
hotfix for v0.1.12

### ISSUE THREAD

**Issue by eric2788** [eric2788/vup_monitors#34]
- 檢查版本更新tag沒有改成0.1.12，將導致每24小時提醒一次0.1.12版本的更新
- 找不到xx指令的處理方法應改成debug訊息防止洗屏

將於幾天內推出 0.1.12.1 以修復上述問題

**Comment by eric2788** [comment]
感覺沒有那麼緊急，因此推遲到幾個月內修復。

**Comment by Marxel-cn** [comment]
https://github.com/eric2788/vup_monitors/commit/62639341475c1c947ead4738c4f1e8d1be6feb0a
